### ISSUE TITLE
websockets with multiple apps?

### ISSUE THREAD

**Issue by ewindso** [aldeed/deploymeteor#3]
Great job with deploymeteor -- thanks for doing this!  

I have deployed 3 Meteor apps to a single server to do some testing.  The first one is over port 80 (default), and the other two are over 50000 and 60000.  (The last 2 are the same app deployed twice, just fyi.)  

WebSockets seem to fail over the first one (port 80), however they work on 50000 and 60000.  

I have checked my security settings on AWS and they seem to be ok.  Thanks for your help.

**Comment by sahanDissanayake** [comment]
@ewindso , @aldeed Since this issue is not closed.... has this been resolved with the newer versions of Meteor and NodeJS ?

**Comment by aldeed** [comment]
No idea, but probably. I haven't used this script for quite a while.
